name: CompatHelper

on:
  schedule:
    - cron: '00 00 * * *'

jobs:
  CompatHelper:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.COMPATHELPER_PRIV }}  # optional
        run: julia -e 'using Pkg, CompatHelper; my_registries = [
                                    Pkg.RegistrySpec(name = "General",
                                      uuid = "23338594-aafe-5451-b93e-139f81909106",
                                      url = "https://github.com/JuliaRegistries/General.git"),
                                    Pkg.RegistrySpec(name = "Miskatonic",
                                      uuid = "79f41a6d-793b-449f-b026-1dc9b55489e6",
                                      url = "https://github.com/Happy-Diode/Miskatonic.git")
                                    ];
                                   CompatHelper.main(; registries = my_registries)'
